services:
  mysql-tareas:
    image: mysql:8.4.5
    container_name: mysql-tareas
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tareasDB
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    container_name: tareas-app
    build: .
    restart: unless-stopped
    depends_on:
      - mysql-tareas
    ports:
      - "8539:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-develop:3306/tareasDB?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

volumes:
  db-data: